name: CI 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev]" pytest-cov

    - name: Run tests and generate coverage report
      run: |
        set -e
        pytest --cov=src/ChemInformant --cov-report=xml -v tests/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4