name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,plotting]" pytest-cov

      - name: Verify plotting libraries
        run: |
          python - <<'PY'
          import sys, PIL, matplotlib, matplotlib.pyplot as plt
          print("Python", sys.version.split()[0])
          print("Pillow", PIL.__version__)
          print("matplotlib", matplotlib.__version__)
          print("pyplot import OK:", plt)
          PY

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest --cov=src/ChemInformant --cov-report=xml -v tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
