name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,plot]" pytest-cov

      - name: Verify plotting libraries
        run: |
          python - <<'PY'
          import sys
          import matplotlib
          import matplotlib.pyplot as plt
          from PIL import __version__ as PILLOW_VERSION

          print("Python", sys.version.split()[0])
          print("Pillow", PILLOW_VERSION)
          print("matplotlib", matplotlib.__version__)
          print("pyplot import OK:", plt)
          PY

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest --cov=src/ChemInformant --cov-report=xml -v tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@412140b9574a4a1595e8ebb4e3ea3b1437146e33
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          # slug: HzaCode/ChemInformant (this is optional)
