name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[dev,plotting]" pytest-cov
    - name: Run tests and print coverage report content
      run: |
        set -e
        export PYTHONPATH=$PYTHONPATH:$(pwd)/src
        echo "PYTHONPATH is now: $PYTHONPATH"
        pytest --cov=src/ChemInformant --cov-report=xml -v tests/
        echo "--- Attempting to print contents of coverage.xml ---"
        cat coverage.xml || echo ">>> coverage.xml file not found! <<<"
        echo "--- End of coverage.xml content ---"
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true 