name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev,plotting]" pytest-cov black isort

      # ---------- Lint ---------- #
      - name: Run Black (check)
        run: black --check src/ tests/

      - name: Run isort (check)
        run: isort --check src/ tests/

      - name: Run Flake8
        run: flake8 src/ tests/

      # ---------- Tests ---------- #
      - name: Run Pytest with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: |
          pytest --cov=src/ChemInformant --cov-report=xml -v tests/

      # ---------- Codecov ---------- #
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
